language: r
cache: packages

r_packages:
  - covr

after_success:
  - Rscript -e 'library(covr); codecov()'

notifications:
  email:
    recipients:
      - mf-walter@web.de
    on_success: change
    on_failure: always
